name: build-auth-server
description: build auth server image

inputs:
  dockerhub-username:
    description: "Login's username dockerhub"
    required: true
  dockerhub-token:
    description: "Login's password dockerhub"
    required: true
  context:
    description: "Dockerfile's directory"
    required: true
  dockerhub-repository:
    description: "Dockerfile's directory"
    required: true

runs:
  using: "composite"
  steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Build tag name
      shell: bash
      run: |
        echo "build_tag=${{ inputs.dockerhub-username }}/${{ inputs.dockerhub-repository }}:$(date +"%Y-%m-%d")" >> $GITHUB_ENV
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ env.build_tag }}
