version: "3"

services:
  auth-server:
    build: ./auth-server
    container_name: auth-service
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=mysql-server
      - MYSQL_PORT=3306
    volumes:
      - ./auth-server:/app/auth-server
  mysql-server:
    image: mysql
    container_name: mysql-service
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql