version: "3"

services:

  auth-server:
    build: ./auth-server
    container_name: auth-service
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=mysql-server
      - MYSQL_PORT=3306
      - AMQP_URL=amqp://guest:guest@rabbitmq-server:5672
    depends_on:
      - mysql-server
      - rabbitmq-server
    volumes:
      - ./auth-server/src:/app/auth-server/src


  send-mail-server:
    build: ./send-mail-server
    container_name: send-mail-service
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq-server:5672
    volumes:
      - ./send-mail-server:/app/send-mail-server
    depends_on:
      rabbitmq-server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:  echo "healthy"
      interval: 20s
      timeout: 10s
      retries: 5

      
  mysql-server:
    image: mysql
    container_name: mysql-service
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
      - ./startup/startup.sql:/startup/startup.sql


  rabbitmq-server:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-service
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test:  echo "healthy"
      interval: 50s
      timeout: 10s
      retries: 5


  sale-server:
    build: ./sale-server
    container_name: sale-service
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - MYSQL_HOST=mysql-server
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    depends_on:
      - mysql-server
    volumes:
      - ./sale-server:/app/sale-server
    healthcheck:
      test:  echo "healthy"
      interval: 50s
      timeout: 10s
      retries: 5

  admin-front-end:
    build: ./admin-front-end
    container_name: admin-front-end
    ports:
      - 5000:5000
    environment:
      - BACKEND_AUTH_URL= auth-server
      - ACKEND_SALE_URL= sale-server
      - PORT= 5000
    volumes:
      - ./admin-front-end:/app/admin-front-end
    depends_on:
      - auth-server
      - sale-server