name: build-auth-server
on: 
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Build the Docker image and push to Dockerhub
        run: |
          export BUILD_TAG = kgks/micro-sale/auth-server:$(date +%s)
          docker build ./auth-server --file Dockerfile --tag BUILD_TAG
          docker push BUILD_TAG
