name: build-auth-server
on: 
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Build tag name
        shell: bash
        run: |
          echo "build_tag=${{ secrets.DOCKERHUB_USERNAME }}/micro-sale/auth-server:$(date +"%Y-%m-%d")" >> $GITHUB_ENV

      - name: Build the Docker image and push to Dockerhub
        run: |
          docker build . --file ./auth-server/Dockerfile --tag ${{ env.build_tag }}
          docker push ${{ env.build_tag }}
