name: build-auth-server
on: 
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Navigate to build directory
        run: cd ./auth-server

      - name: Build tag name
        shell: bash
        run: |
          echo "build_tag=${{ secrets.DOCKERHUB_USERNAME }}/micro-sale/auth-server:$(date +"%Y-%m-%d")" >> $GITHUB_ENV

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image and push to Dockerhub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.build_tag }}
