name: build
on: 
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Build tag name
        uses: ./.github/actions/build-image-server
        with:
            dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
            dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
            context: ./auth-server
            dockerhub-repository: micro-sale-auth-server