name: build
on: 
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Build auth server
        uses: ./.github/actions/build-image-server
        with:
            dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
            dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
            context: ./auth-server
            dockerhub-repository: micro-sale-auth-server
      - 
        name: Build sale server
        uses: ./.github/actions/build-image-server
        with:
            dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
            dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
            context: ./sale-server
            dockerhub-repository: micro-sale-sale-server
      - 
        name: Build admin frontend server
        uses: ./.github/actions/build-image-server
        with:
            dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
            dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
            context: ./admin-front-end
            dockerhub-repository: micro-sale-admin-frontend-server
      - 
        name: Build send mail server
        uses: ./.github/actions/build-image-server
        with:
            dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
            dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
            context: ./send-mail-server
            dockerhub-repository: micro-sale-send-mail-server